Items:
  item-name: '&6Gigadrill'
  lores:
    - '&bFirst Line'
    - '&6Second Line'
  type:
    - DIAMOND_PICKAXE
    - GOLD_PICKAXE
    - IRON_PICKAXE
    - STONE_PICKAXE
    - WOOD_PICKAXE