##################################
#       PickaxeEggs plugin       #
#               by               #
#          SpaicyGaming          #
##################################

Items:
  item-name: '&6Gigadrill'
  # snowball or egg
  projectile: snowball
  # sounds list: https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  soundEffect: BLOCK_STONE_BREAK
  radius: 2
  lores:
    - '&bFirst Line'
    - '&6Second Line'
  type:
    - DIAMOND_PICKAXE
    - GOLD_PICKAXE
    - IRON_PICKAXE
    - STONE_PICKAXE
    - WOOD_PICKAXE